name: documentation

on:
  pull_request:
    branches: [docusaurus]
  push:
    branches: [docusaurus]

jobs:
 checks:
   if: github.event_name != 'push'
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v1
     - uses: actions/setup-node@v1
       with:
         node-version: '12.x'
         run: |
          npm ci
          npm run build
 gh-release:
   if: github.event_name != 'pull_request'
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: install
      working-directory: ./website
      run: npm install

    - name: build
      working-directory: ./website
      run: npm run build

    - name: deploy
      uses: peaceiris/actions-gh-pages@v2.3.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./website/build/aut-docs
